language: php

dist: xenial

branches:
  only:
    - master

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - sudo apt-get update -q
  - composer self-update
  - if [ "$COMPOSER_FLAGS" == "--prefer-lowest" ]; then composer require "roave/security-advisories" dev-master --no-update; fi;

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit --verbose
